# Generated by Django 4.1.4 on 2022-12-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='phone_num',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='picture_url',
        ),
    ]
